// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSULSnZzhyy_A0VwevXHsY2_qXr4voRZE',
    appId: '1:124288562306:web:ca4da12db5251e7a99f09b',
    messagingSenderId: '124288562306',
    projectId: 'moviefilx-76186',
    authDomain: 'moviefilx-76186.firebaseapp.com',
    storageBucket: 'moviefilx-76186.appspot.com',
    measurementId: 'G-2T5L2VBV94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4idoqWYp1oPCMo1Tb_u_wE9A7WGWptbk',
    appId: '1:124288562306:android:2bc9330014995f9c99f09b',
    messagingSenderId: '124288562306',
    projectId: 'moviefilx-76186',
    storageBucket: 'moviefilx-76186.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9tzivJwgHldso45slL2aQsp_JsPfXq2I',
    appId: '1:124288562306:ios:cca09c135c2eb9f299f09b',
    messagingSenderId: '124288562306',
    projectId: 'moviefilx-76186',
    storageBucket: 'moviefilx-76186.appspot.com',
    iosBundleId: 'com.example.movieflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9tzivJwgHldso45slL2aQsp_JsPfXq2I',
    appId: '1:124288562306:ios:cca09c135c2eb9f299f09b',
    messagingSenderId: '124288562306',
    projectId: 'moviefilx-76186',
    storageBucket: 'moviefilx-76186.appspot.com',
    iosBundleId: 'com.example.movieflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSULSnZzhyy_A0VwevXHsY2_qXr4voRZE',
    appId: '1:124288562306:web:64fc051b5721db6399f09b',
    messagingSenderId: '124288562306',
    projectId: 'moviefilx-76186',
    authDomain: 'moviefilx-76186.firebaseapp.com',
    storageBucket: 'moviefilx-76186.appspot.com',
    measurementId: 'G-K4CMX7QRBM',
  );
}
